### PR TITLE
fix build with --no-default-features

### PR DESCRIPTION
**Pull request by Fabian-Gruenbichler**
a bit ugly, but works.

Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>

### CODE REVIEW

**Comment by tarcieri** [comment]
Note that a build for `--no-default-features --lib` is already tested for:

https://github.com/RustSec/cargo-lock/blob/master/.github/workflows/rust.yml#L45

What are you hoping to accomplish with this?

**Comment by Fabian-Gruenbichler** [comment]
I'm packaging cargo-lock for Debian, and Debian's tooling (by default) runs (as part of CI/regression detection) `cargo test --all-targets` individually with

- `--all-features`
- `--no-default-features`
- `--features default`
- and once for each feature individually with `--features $FEATURE`

the second one breaks for cargo-lock, since cargo is unable to even build it with those parameters. It's of course also possible to skip the no-default-features test, but that might mean other feature-related regressions are not detected properly/early on.

I don't know of a way to say that compiling the bin requires feature foo, which would of course make more sense and be more elegant.

**Comment by tarcieri** [comment]
Interesting. I'd imagine a lot of crates don't pass all tests with `--no-default-features`, especially ones which provide an optional `cli`-gated CLI feature (I just checked `cargo-edit` as another example), but also any crate which includes toplevel documentation which is in some way feature-gated (I guess this is where `doc(cfg(feature(...))` might help.

**Comment by Fabian-Gruenbichler** [comment]
On February 14, 2020 4:18 pm, Tony Arcieri wrote:
> Interesting. I'd imagine a lot of crates don't pass all tests with `--no-default-features`, especially ones which provide an optional `cli`-gated CLI feature (I just checked `cargo-edit` as another example), but also any crate which includes toplevel documentation which is in some way feature-gated (I guess this is where `doc(cfg(feature(...))` might help.

cargo-edit is not the best example, as that one fails to even build with 
`--no-default-features --lib` ;)

that being said, feel free to close this until a more elegant solution 
(like conditionalizing bin crate building on features being enabled) is 
available, and we can disable that specific test invocation on the 
Debian side.

**Pull request closed without merging**
