### PR TITLE
Support [[dependencies]] without versions

### PR DESCRIPTION
**Pull request by tarcieri**
Adds example `Cargo.lock` generated from `rust-lang/rust` (i.e. rustc) which contains dependencies with no associated version.

This necessitates changing `Dependency::version` to be an `Option<Version>`, a semver breaking change.

### CODE REVIEW

**Comment by nox** [comment]
Is there a way to use `cargo-lock` to write back a manifest it parsed, to go from the new to the old format?

Context: https://mozilla.logbot.info/servo/20191001#c16657873

**Comment by tarcieri** [comment]
@nox `cargo_lock::Lockfile` impls `ToString`, so you can try that and see if it outputs what you're expecting

**Comment by nox** [comment]
Perfect, thanks!

**Comment by nox** [comment]
https://github.com/nox/cargo-old-lock

**Pull request merged**
